version: "3.0"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123
      - PGDATA=/var/lib/postgresql/pgdata/
      - POSTGRES_DB=ithilleldb
    volumes:
      - pgdata:/var/lib/postgresql/pgdata/
    ports:
      - 5432:5432
  web:
    build: .
    volumes:
      - .:/src/
    depends_on:
      - db
    environment:
        DJANGO_SETTINGS_MODULE: 'settings.prod'
    ports:
      - 8000:8000
    command: /bin/bash -c 'pip install -r requirements.txt && invoke run'

volumes:
  pgdata: { }