version: 2.1

jobs:
  flake8:
    docker:
      - image: prospector
    steps:
      - checkout
      - run:
          name: "Prospector check"
          command: "prospector apps"

workflows:
  check-code:
    jobs:
      - flake8
