version: 2.1

jobs:
  flake8:
    docker:
      - image: alpine/flake8
    steps:
      - checkout
      - run:
          name: "Flake8 check"
          command: "flake8"

workflows:
  check-code:
    jobs:
      - flake8
