version: 2.1

jobs:
  prospector:
    docker:
      - image: ckleemann/prospector
    steps:
      - checkout
      - run:
          name: "Prospector check"
          command: "prospector apps"

workflows:
  check-code:
    jobs:
      - prospector
