# Generated by Django 4.0.3 on 2022-07-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_year_movie_start_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='start_year',
            new_name='year',
        ),
    ]
