# Generated by Django 4.0.3 on 2022-07-18 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_start_year_movie_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='year',
            new_name='date',
        ),
    ]
