# Generated by Django 4.0.3 on 2022-03-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(to='lms.student'),
        ),
    ]
