# Generated by Django 4.0.3 on 2022-03-18 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_class_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Group',
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.group'),
        ),
    ]
