# Generated by Django 4.0.2 on 2022-04-04 15:24

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=255, null=True, verbose_name='IMDB id')),
                ('title_type', models.CharField(choices=[('short', 'Short'), ('movie', 'Movie')], max_length=255, verbose_name='Type of the title')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_adult', models.BooleanField(verbose_name='Is Adult')),
                ('date', models.DateField(null=True, verbose_name='Release Date')),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None, verbose_name='Genres')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=255, null=True, verbose_name='IMDB id')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('death_date', models.DateField(verbose_name='Death Date')),
            ],
        ),
        migrations.CreateModel(
            name='PersonMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Ordering')),
                ('category', models.CharField(max_length=255, verbose_name='Category')),
                ('job', models.CharField(max_length=255, verbose_name='Job')),
                ('characters', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None, verbose_name='Characters')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imdb.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imdb.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='movies',
            field=models.ManyToManyField(through='imdb.PersonMovie', to='imdb.Movie'),
        ),
    ]
