# Generated by Django 4.0.2 on 2022-04-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imdb", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="birth_date",
            field=models.DateField(null=True, verbose_name="Birth Date"),
        ),
        migrations.AlterField(
            model_name="person",
            name="death_date",
            field=models.DateField(null=True, verbose_name="Death Date"),
        ),
    ]
