# Generated by Django 4.0.3 on 2022-07-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0003_alter_personmovie_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='movies',
            field=models.ManyToManyField(related_name='persons', through='imdb.PersonMovie', to='imdb.movie'),
        ),
    ]
